version: '3'

services:
  api:
    build: .
    ports:
      - 4000:4000
      - 9229:9229
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - 27017:27017
